// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technologieInternetowe.DAL;

#nullable disable

namespace technologieInternetowe.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20260304081428_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("technologieInternetowe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action films",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy films",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama films",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Horror films",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Science Fiction films",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Romantic films",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Thriller films",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Animated films",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Documentary films",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fantasy films",
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("technologieInternetowe.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 5,
                            Desc = "A mind-bending thriller",
                            Director = "Christopher Nolan",
                            Price = 9.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 1,
                            Desc = "A superhero crime film",
                            Director = "Christopher Nolan",
                            Price = 9.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 1,
                            Desc = "Crime anthology film",
                            Director = "Quentin Tarantino",
                            Price = 7.99m,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 3,
                            Desc = "A crime family saga",
                            Director = "Francis Ford Coppola",
                            Price = 8.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 3,
                            Desc = "A story of hope",
                            Director = "Frank Darabont",
                            Price = 8.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 5,
                            Desc = "A sci-fi action film",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Price = 9.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 7,
                            Desc = "A psychological thriller",
                            Director = "Jonathan Demme",
                            Price = 7.99m,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 8,
                            Desc = "An animated adventure",
                            Director = "Roger Allers, Rob Minkoff",
                            Price = 6.99m,
                            Title = "The Lion King"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 9,
                            Desc = "A breathtaking nature documentary",
                            Director = "David Attenborough",
                            Price = 5.99m,
                            Title = "Planet Earth II"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 10,
                            Desc = "An epic fantasy adventure",
                            Director = "Peter Jackson",
                            Price = 9.99m,
                            Title = "The Lord of the Rings"
                        });
                });

            modelBuilder.Entity("technologieInternetowe.Models.Film", b =>
                {
                    b.HasOne("technologieInternetowe.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("technologieInternetowe.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
