// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technologieInternetowe.DAL;

#nullable disable

namespace technologieInternetowe.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20260513062848_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("technologieInternetowe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action films",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy films",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama films",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Horror films",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Science Fiction films",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Romantic films",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Thriller films",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Animated films",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Documentary films",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fantasy films",
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("technologieInternetowe.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 5,
                            Desc = "A mind-bending thriller",
                            Director = "Christopher Nolan",
                            Price = 9.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 1,
                            Desc = "A superhero crime film",
                            Director = "Christopher Nolan",
                            Price = 9.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 1,
                            Desc = "Crime anthology film",
                            Director = "Quentin Tarantino",
                            Price = 7.99m,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 3,
                            Desc = "A crime family saga",
                            Director = "Francis Ford Coppola",
                            Price = 8.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 3,
                            Desc = "A story of hope",
                            Director = "Frank Darabont",
                            Price = 8.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 5,
                            Desc = "A sci-fi action film",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Price = 9.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 7,
                            Desc = "A psychological thriller",
                            Director = "Jonathan Demme",
                            Price = 7.99m,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 8,
                            Desc = "An animated adventure",
                            Director = "Roger Allers, Rob Minkoff",
                            Price = 6.99m,
                            Title = "The Lion King"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 9,
                            Desc = "A breathtaking nature documentary",
                            Director = "David Attenborough",
                            Price = 5.99m,
                            Title = "Planet Earth II"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 10,
                            Desc = "An epic fantasy adventure",
                            Director = "Peter Jackson",
                            Price = 9.99m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            FilmId = 111,
                            CategoryId = 3,
                            Desc = "A man with a low IQ has great accomplishments.",
                            Director = "Robert Zemeckis",
                            Price = 7.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            FilmId = 112,
                            CategoryId = 5,
                            Desc = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Price = 10.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 113,
                            CategoryId = 1,
                            Desc = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
                            Director = "Ridley Scott",
                            Price = 8.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            FilmId = 114,
                            CategoryId = 3,
                            Desc = "The lives of guards on Death Row are affected by one of their charges.",
                            Director = "Frank Darabont",
                            Price = 6.99m,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            FilmId = 115,
                            CategoryId = 1,
                            Desc = "Earth's mightiest heroes must come together and learn to fight as a team.",
                            Director = "Joss Whedon",
                            Price = 11.99m,
                            Title = "The Avengers"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technologieInternetowe.Models.Film", b =>
                {
                    b.HasOne("technologieInternetowe.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("technologieInternetowe.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
